config_version = "0"

exclude_patterns = [
  "**/*",
  "!src/**",
  "!src-tauri/**",
]

[smells]
mode = "comment"

[smells.function_complexity]
threshold = 80

[smells.file_complexity]
threshold = 100

[smells.return_statements]
enabled = false

[[source]]
name = "default"
default = true
