name: Build and Release Tauri App

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
          libgtk-3-dev \
          libgdk3-dev \
          libglib2.0-dev \
          libwebkit2gtk-4.0-dev \
          libsoup2.4-dev \
          libjavascriptcoregtk-4.0-dev \
          libgstreamer1.0-dev \
          libgstreamer-plugins-base1.0-dev \
          libnotify-dev \
          libdbus-glib-1-dev \
          libappindicator3-dev

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Tauri app
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_KEY }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        run: npm run tauri build

      - name: Update latest.json
        run: |
          VERSION=$(jq -r '.package.version' src-tauri/tauri.conf.json)
          jq --arg version "v$VERSION" --arg signature "$(cat src-tauri/target/release/bundle/nsis/Inventory_${VERSION}_x64-setup.nsis.zip.sig)" \
             '.version = $version | .platforms."windows-x86_64".signature = $signature' \
             latest.json > updated_latest.json
          mv updated_latest.json latest.json

      - name: Upload Release Asset
        id: upload-release
        uses: actions/upload-artifact@v3
        with:
          name: Inventory App
          path: src-tauri/target/release/bundle/nsis/Inventory_${{ github.ref }}_x64-setup.nsis.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
