name: Vitest

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '24'

    - name: Install modules
      run: npm ci
      
    - name: Run Vitest
      run: npm run test:unit
